// app/[locale]/components/scroll-top.tsx
"use client";

import { faArrowUp } from "@fortawesome/free-solid-svg-icons";
import { useTranslations } from "next-intl";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useEffect, useState } from "react";

export default function ScrollTop()
{
    const messages = useTranslations( "landing" );
    const [ showButton, setShowButton ] = useState( false );

    const scrollToTop = () => window.scrollTo( { top: 0, behavior: "smooth" } );
    const onScroll = () => setShowButton( window.scrollY > 200 );

    // https://github.com/vercel/next.js/issues/6132#issuecomment-790623507
    useEffect( () =>
    {
        onScroll();

        window.addEventListener( "scroll", onScroll );

        return () => window.removeEventListener( "scroll", onScroll );
    }, [] );

    return (
        showButton && (
            <aside>
                <button
                    type="button"
                    title={messages( "scroll_top" )}
                    onClick={scrollToTop}
                    aria-label={messages( "scroll_top" )}
                >
                    <FontAwesomeIcon icon={faArrowUp} />
                </button>
            </aside>
        )
    );
}

// src/lib/components/ScrollTop.svelte
<script lang="ts">
    import * as m from "$lib/locales/messages";
    import { onMount } from "svelte";

    let showButton = $state( false );

    const scrollToTop = () => window.scrollTo( { top: 0, behavior: "smooth" } );
    const onScroll = () => ( showButton = window.scrollY > 200 );

    onMount( () =>
    {
        onScroll();

        window.addEventListener( "scroll", onScroll );

        return () => window.removeEventListener( "scroll", onScroll );
    } );
</script>

{#if showButton}
    <aside>
        <button type="button" title={m.landing_scroll_top()} onclick={scrollToTop} aria-label={m.landing_scroll_top()}>
            <i class="fa-solid fa-arrow-up"></i>
        </button>
    </aside>
{/if}
