// app/components/skill-filter.tsx
//
// Composant de filtrage de la section des compétences.
//

"use client";

import { type ChangeEvent } from "react";
import { useSearchParams, useRouter } from "next/navigation";

import { useTranslation } from "@/utilities/ClientTranslations";
import type { SkillAttributes } from "@/interfaces/Skill";

export default function SkillFilter( { skills }: { skills: SkillAttributes[] } )
{
	// Déclaration des constantes.
	const parameters = useSearchParams();
	const router = useRouter();
	const filter = parameters.get( "filter" ) ?? "";

	// Déclaration des variables d'état.
	const { t } = useTranslation();

	// Mise à jour du filtre des compétences.
	const updateSkillFilter = ( event: ChangeEvent<HTMLInputElement> ) =>
	{
		const url = new URLSearchParams( parameters );
		url.set( "filter", event.currentTarget.id );

		router.push( url ? `?${ url.toString() }` : url );
	};

	// Affichage du rendu HTML du composant.
	return (
		<section id="skills">
			{/* Section des compétences */}
			<h2>{t( "pages.index.header_skills" )}</h2>

			{/* Filtre des compétences */}
			<article>
				<input
					id="all"
					type="radio"
					name="skills"
					checked={filter === "all" || filter === ""}
					onChange={updateSkillFilter}
				/>
				<label htmlFor="all">{t( "pages.index.filter_all" )}</label>

				<input
					id="front"
					type="radio"
					name="skills"
					checked={filter === "front"}
					onChange={updateSkillFilter}
				/>
				<label htmlFor="front">{t( "pages.index.filter_front" )}</label>

				<input
					id="back"
					type="radio"
					name="skills"
					checked={filter === "back"}
					onChange={updateSkillFilter}
				/>
				<label htmlFor="back">{t( "pages.index.filter_back" )}</label>

				<input
					id="other"
					type="radio"
					name="skills"
					checked={filter === "other"}
					onChange={updateSkillFilter}
				/>
				<label htmlFor="other">{t( "pages.index.filter_other" )}</label>
			</article>

			{/* Génération des compétences */}
			<article>
				{Object.entries( skills ).map( ( [ key, value ] ) =>
				{
					if ( filter === "all" || value.type.includes( filter ) )
					{
						const colored =
							key !== "lua"
							&& key !== "wordpress"
							&& value.icon !== "original";

						return (
							<div key={key}>
								<i
									className={`devicon-${ key }-${
										value.icon + ( colored ? " colored" : "" )
									}`}
								/>

								<span>{value.name}</span>
							</div>
						);
					}

					return null;
				} )}
			</article>
		</section>
	);
}

// src/lib/components/SkillFilter.svelte
<script lang="ts">
    import * as m from "$lib/locales/messages";
    import type { Skill } from "$lib";

    let { skills }: { skills: Record<string, Skill> } = $props();

    let filter = $state( "all" );

    const updateFilter = ( value: string ) =>
    {
        filter = value;

        const url = new URL( window.location.href );
        url.searchParams.set( "filter", value );

        history.pushState( null, "", url.toString() );
    };
</script>

<section id="skills">
    <h2>{m.landing_header_skills()}</h2>

    <ul>
        <li>
            <input
                id="all"
                type="radio"
                name="skills"
                checked={filter === "all"}
                onchange={() => updateFilter( "all" )}
            />
            <label for="all">{m.landing_filter_all()}</label>
        </li>

        <li>
            <input
                id="front"
                type="radio"
                name="skills"
                checked={filter === "front"}
                onchange={() => updateFilter( "front" )}
            />
            <label for="front">{m.landing_filter_front()}</label>
        </li>

        <li>
            <input
                id="back"
                type="radio"
                name="skills"
                checked={filter === "back"}
                onchange={() => updateFilter( "back" )}
            />
            <label for="back">{m.landing_filter_back()}</label>
        </li>

        <li>
            <input
                id="other"
                type="radio"
                name="skills"
                checked={filter === "other"}
                onchange={() => updateFilter( "other" )}
            />
            <label for="other">{m.landing_filter_other()}</label>
        </li>
    </ul>

    <ul>
        {#each Object.entries( skills ) as [ key, value ] ( key )}
            {#if filter === "all" || ( Array.isArray( value.type ) ? value.type.includes( filter ) : value.type === filter )}
                <li>
                    <i class={`devicon-${ key }-${ value.icon }`}></i>
                    {value.name}
                </li>
            {/if}
        {/each}
    </ul>
</section>
