// app/[locale]/components/skill-filter.tsx
"use client";

import { useTranslations } from "next-intl";
import { useSearchParams } from "next/navigation";
import { type ChangeEvent } from "react";
import type { SkillAttributes } from "@/interfaces/Skill";

export default function SkillFilter( { skills }: Readonly<{ skills: SkillAttributes[] }> )
{
    const parameters = useSearchParams();
    const messages = useTranslations( "landing" );
    const filter = parameters.get( "filter" ) ?? "";

    const updateSkillFilter = ( event: ChangeEvent<HTMLInputElement> ) =>
    {
        const url = new URLSearchParams( parameters );
        url.set( "filter", event.currentTarget.id );

        window.history.pushState( null, "", `?${ url }` );
    };

    return (
        <section id="skills">
            <h2>{messages( "header_skills" )}</h2>

            <ul>
                <li>
                    <input
                        id="all"
                        type="radio"
                        name="skills"
                        checked={filter === "all" || filter === ""}
                        onChange={updateSkillFilter}
                    />

                    <label htmlFor="all">{messages( "filter_all" )}</label>
                </li>

                <li>
                    <input
                        id="front"
                        type="radio"
                        name="skills"
                        checked={filter === "front"}
                        onChange={updateSkillFilter}
                    />

                    <label htmlFor="front">{messages( "filter_front" )}</label>
                </li>

                <li>
                    <input
                        id="back"
                        type="radio"
                        name="skills"
                        checked={filter === "back"}
                        onChange={updateSkillFilter}
                    />

                    <label htmlFor="back">{messages( "filter_back" )}</label>
                </li>

                <li>
                    <input
                        id="other"
                        type="radio"
                        name="skills"
                        checked={filter === "other"}
                        onChange={updateSkillFilter}
                    />

                    <label htmlFor="other">{messages( "filter_other" )}</label>
                </li>
            </ul>

            <ul>
                {Object.entries( skills ).map( ( [ key, value ] ) =>
                {
                    if ( filter === "" || filter === "all" || value.type.includes( filter ) )
                    {
                        return (
                            <li key={key}>
                                <i className={`devicon-${ key }-${ value.icon }`} />

                                {value.name}
                            </li>
                        );
                    }

                    return null;
                } )}
            </ul>
        </section>
    );
}

// src/lib/components/SkillFilter.svelte
<script lang="ts">
    import * as m from "$lib/locales/messages";
    import type { Skill } from "$lib";

    let { skills }: { skills: Record<string, Skill> } = $props();

    let filter = $state( "all" );

    const updateFilter = ( value: string ) =>
    {
        filter = value;

        const url = new URL( window.location.href );
        url.searchParams.set( "filter", value );

        history.pushState( null, "", url.toString() );
    };
</script>

<section id="skills">
    <h2>{m.landing_header_skills()}</h2>

    <ul>
        <li>
            <input
                id="all"
                type="radio"
                name="skills"
                checked={filter === "all"}
                onchange={() => updateFilter( "all" )}
            />
            <label for="all">{m.landing_filter_all()}</label>
        </li>

        <li>
            <input
                id="front"
                type="radio"
                name="skills"
                checked={filter === "front"}
                onchange={() => updateFilter( "front" )}
            />
            <label for="front">{m.landing_filter_front()}</label>
        </li>

        <li>
            <input
                id="back"
                type="radio"
                name="skills"
                checked={filter === "back"}
                onchange={() => updateFilter( "back" )}
            />
            <label for="back">{m.landing_filter_back()}</label>
        </li>

        <li>
            <input
                id="other"
                type="radio"
                name="skills"
                checked={filter === "other"}
                onchange={() => updateFilter( "other" )}
            />
            <label for="other">{m.landing_filter_other()}</label>
        </li>
    </ul>

    <ul>
        {#each Object.entries( skills ) as [ key, value ] ( key )}
            {#if filter === "all" || ( Array.isArray( value.type ) ? value.type.includes( filter ) : value.type === filter )}
                <li>
                    <i class={`devicon-${ key }-${ value.icon }`}></i>
                    {value.name}
                </li>
            {/if}
        {/each}
    </ul>
</section>
